#pragma config(Sensor, in1,    turPot,              sensorPotentiometer)
#pragma config(Sensor, dgtl1,  irNorth,             sensorDigitalIn)
#pragma config(Sensor, dgtl2,  irEast,              sensorDigitalIn)
#pragma config(Sensor, dgtl3,  irSouth,             sensorDigitalIn)
#pragma config(Sensor, dgtl4,  irWest,              sensorDigitalIn)
#pragma config(Sensor, dgtl7,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port3,           pServo,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           fServo,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           tMotor,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//digital sensors - four IR direction detectors, ultrasound input and output (inches)
//motor/servo ports - pan and fire servos, turret motor
//fire servo - negative fires. positive stops firing. see "fire test.c" file
//turret motor - CCW is negative. CW is positive. see "turret test.c" file

//********************************Global Variables and Constants********************************
typedef enum
{
  North,
  East,
  South,
  West
} IRSensorDirection;

IRSensorDirection curDir = North;
IRSensorDirection lastDir = South;
int nCount = 0, wCount = 0, sCount = 0, eCount = 0;
bool doFire = false;

//main constants
const int NUM_FIRED = 30;

//IR constants
const int NUM_READINGS = 10;

//turret constants
//clockwise speed for 36 or greater, need 38 to reach full range
//counterclockwise speed for -24 or less
const int MAX_CCW_POT_VAL = 3700;
const int MIN_CW_POT_VAL = 400;
const int MIN_CCW_SPEED = -24;
const int MIN_CW_SPEED = 38;
const int TURRET_CENTER = 1865;

//firing constants
const int FIRE_SERVO = -40;
const int STOP_FIRE_SERVO = 50;
const int FIRE_TIME = 200;



//************************************Function Prototypes****************************************
//RobotC does not allow passing arrays!!!!
//RobotC does not allow for pointers... yay global variables!!!!
//  - this is to trim down space taken up by RobotC firmware

//IR Detection Task subroutines
void getInstantDirection();
void setModeDirection();

//Turret Control subroutines
void tSpeed( int speed );

//main subroutines
void setCenter();

//**************************************IR Detection*********************************************
task IRDetectionTask()
{

  while( true )
  {
    for( int numCount = 0; numCount < NUM_READINGS; numCount++ )
    {
      getInstantDirection();

    }//end for numCount

    setModeDirection();

    nCount = 0;
    wCount = 0;
    sCount = 0;
    eCount = 0;

  }//end while true

}//end IRDetectionTask

void getInstantDirection()
{
  if( SensorValue[ irNorth ] == 0 )
    nCount++;
  else if( SensorValue[ irWest ] == 0 )
    wCount++;
  else if( SensorValue[ irEast ] == 0 )
    eCount++;
  else if( SensorValue[ irSouth ] == 0 )
    sCount++;

}//end getInstantDirection

void setModeDirection()
{
  IRSensorDirection maxDir = North;

  int max = nCount;

  if( max == NUM_READINGS )
    doFire = true;
  else doFire = false;

  if( wCount > max )
  {
    maxDir = West;
    max = wCount;
  }//end if

  if( eCount > max )
  {
    maxDir = East;
    max = eCount;
  }//end if

  if( sCount > max )
    maxDir = South;

  //only want to change curDir once each method call so maxDir is used
  lastDir = curDir;
  curDir = maxDir;

}//end setModeDirection


//**************************************Turret Control********************************************
task TurretTask()
{
  while( true )
  {
    int potVal = SensorValue[turPot];

    //keep it within bounds so wires dont get destroyed
    if( potVal >= MAX_CCW_POT_VAL && ( curDir == West || curDir == North ) )
    {
      tSpeed( 0 ); // stop the turret

    }//end if
    else if( potVal <= MIN_CW_POT_VAL && ( curDir == East || curDir == North ) )
    {
      tSpeed( 0 ); // stop the turret

    }//end else
    else
    {
      switch( curDir )
      {
        case West:
          switch( lastDir )
          {
            case West:
            case East: tSpeed( MIN_CCW_SPEED - 5 );
              break;
            case North: tSpeed( MIN_CCW_SPEED );
              break;
          }// end switch west lastDir
        break;
        case East:
          switch( lastDir )
          {
            case East:
            case West: tSpeed( MIN_CW_SPEED + 5 );
              break;
            case North: tSpeed( MIN_CW_SPEED );
              break;
          }// end switch east lastDir
        break;
        case North:
          switch( lastDir )
          {
            case North: tSpeed( 0 );
              break;
            case West: tSpeed( MIN_CW_SPEED - 3 );
              break;
            case East: tSpeed( MIN_CCW_SPEED + 3 );
              break;
          }//end switch north lastDir
        break;

      }//end switch curDir

    }//end else

  }//end while

}//end turretTask

void tSpeed( int speed )
{
  motor[tMotor] = speed;

}//end stopT


//***************************************Main****************************************************
//Initiate Primary Tasks
//Assign Task Priority
//Ends Program when necessary
//determines when to fire the gun
task main()
{
  wait1Msec(5000);

  setCenter();

  StartTask( IRDetectionTask );
  StartTask( TurretTask );

  int fireCount = 0;

  while( fireCount < NUM_FIRED )
  {
    if( curDir == North && lastDir == North && doFire == true )
    {
      motor[fServo] = FIRE_SERVO; //fire
      wait1Msec(FIRE_TIME); //wait
      motor[fServo] = STOP_FIRE_SERVO; //stop firing
      fireCount++;

    }//end if

  }//end while

  motor[fServo] = 50; //stop firing
  wait1Msec(FIRE_TIME);

  StopAllTasks();

}//end main

//this function centers the turret before tracking the target
//potentiometer is centered at approximately 1865
void setCenter()
{
  if( sensorValue[turPot] > TURRET_CENTER )
  {
    motor[tMotor] = MIN_CW_SPEED;

    while( sensorValue[turPot] > TURRET_CENTER )
      {/*wait*/} //end while

  }//end if
  else
  {
    motor[tMotor] = MIN_CCW_SPEED;

    while( sensorValue[turPot] < TURRET_CENTER )
      {/*wait*/}//end while
  }//end else

  motor[tMotor] = 0;

  motor[pServo] = 0;
  wait1Msec(FIRE_TIME);

}//end setCenter
