#pragma config(Sensor, dgtl1,  irNorth,             sensorDigitalIn)
#pragma config(Sensor, dgtl2,  irEast,              sensorDigitalIn)
#pragma config(Sensor, dgtl3,  irSouth,             sensorDigitalIn)
#pragma config(Sensor, dgtl4,  irWest,              sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//used to determine direction
typedef enum
{
  North,
  East,
  South,
  West
} direction;

direction getDir();
direction determineHighCount( int nc, int ec, int sc, int wc );
void displayDir( direction endDir );

task main()
{

  int readingCount = 0;
  direction mainDir = north;
  int nCount = 0;
  int eCount = 0;
  int sCount = 0;
  int wCount = 0;
  direction finalDir = north;


  //as the IR sensor jumps around, i will take 10 readings (maybe more if necessary) then decide which direction
  //the sensor registers the most. then i will adjust the robot accordingly.

  while( true )
  {
    while( readingCount < 10 )
    {
      mainDir = getDir();

      switch( mainDir )
      {
        case north: nCount++;
            break;
        case east: eCount++;
            break;
        case south: sCount++;
            break;
        case west: wCount++;
            break;

       }//switch mainDir

       readingCount++;

    }//while count

    //robot make decision
    finalDir = determineHighCount(nCount, eCount, sCount, wCount);
    displayDir(finalDir);

    //reset values
    readingCount = 0;
    nCount = 0;
    eCount = 0;
    sCount = 0;
    wCount = 0;

  }//while true

}//main

//this method gets the instantaneous IR sensor reading. it returns the direction as
//enumerated type "direction" variable "dir"
direction getDir()
{
   int northDir = SensorValue[irNorth];
   int eastDir = SensorValue[irEast];
   int southDir = SensorValue[irSouth];
   int westDir = SensorValue[irWest];
   static direction dir = north;

   //0 indicates the other IR beacon was found in the corresponding direction
   //1 indicates beacon not found in that direction
   if( northDir == 0 )
     dir = north;
   else if( eastDir == 0 )
     dir = east;
   else if( southDir == 0 )
     dir = south;
   else if( westDir == 0 )
     dir = west;

   return dir;

}//getDir

//determine the direction that the sensor detected the most
direction determineHighCount( int nc, int ec, int sc, int wc )
{
  int max = nc;
  direction thisDir = north;

  if( ec > max )
  {
    max = ec;
    thisDir = east;
  }//if

  if( sc > max )
  {
    max = sc;
    thisDir = south;
  }//if

  if( wc > max )
  {
    max = wc;
    thisDir = west;
  }//if

  return thisDir;

}//determineHighCount


//display final direction on debug window
void displayDir( direction endDir )
{
  string lastDir = "";

  switch( endDir )
  {
    case north: strcpy(lastDir, "North");
        break;
    case east:  strcpy(lastDir, "East");
        break;
    case south: strcpy(lastDir, "South");
        break;
    case west:  strcpy(lastDir, "West");
        break;

  }//switch

}//printDir
