#pragma config(Sensor, in1,    turPot,              sensorPotentiometer)
#pragma config(Motor,  port5,           tMotor,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task Scan()
{
  int potVal = 0;

  typedef enum
  {
    ccw,
    cw
  } direction;

  direction dir = ccw;

  while( true )
  {
    potVal = SensorValue[turPot];

    switch (dir)
    {
      case ccw: motor[tMotor] = -28;
              if( potVal >= 4000)
                dir = cw;
              break;

      case cw: motor[tMotor] = 45;
              if( potVal <= 400 )
                dir = ccw;
              break;

    }//switch


  }//while

}//scan

task main()
{
  //4000 is counter clockwise limit
  //1865 is centered
  //400 is clockwise limit

  //clockwise for 36 or greater, need 38 to reach full range
  //counterclockwise for -24 or less

  StartTask(Scan);

  while (true)
  {

  }//while
}//main
