#pragma config(Sensor, dgtl5,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port6,           blMotor,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           brMotor,       tmotorNormal, openLoop)
#pragma config(Motor,  port8,           flMotor,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port9,           frMotor,       tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnLeft();

task main()
{
  wait1Msec(1000);

  int contMoving = 0;
  bool obstacleDetected = false;

  while( contMoving <= 3 )
  {
    motor[blMotor] = 127;
    motor[brMotor] = 127;
    motor[flMotor] = 127;
    motor[frMotor] = 127;

    if( SensorValue[sonarSensor] < 3 )
    {
      obstacleDetected = true;
      turnLeft();
      wait1Msec(2000);
      contMoving++;
      obstacleDetected = false;

    }//if

  }//while

}//main

void turnLeft()
{
  //back up
  motor[blMotor] = -127;
  motor[brMotor] = -127;
  motor[flMotor]= -127;
  motor[frMotor] = -127;
  wait1Msec(1000);

  //turn perpendicular to the left
  motor[blMotor] = -127;
  motor[flMotor] = -127;
  motor[brMotor] = 127;
  motor[frMotor] = 127;
  wait1Msec(750);

}//turnLeft
